version: '3.8'

services:
  api:
    build:
      context: .  # The location of the Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}  # Ensure this environment variable is passed
    env_file:  # Load other environment variables from the .env file
      - .env
    networks:
      - api_forum-network
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - api_forum-network

networks:
  api_forum-network:
    driver: bridge
